export const NAMES_LIST = [
  "Daren Sammy",
  "Josh Hazlewood",
  "Imran Khan",
  "Arbab Tufail",
  "Uzair Ibrar",
  "Haris Khan",
  "Wasiq Sheique",
  "Zahra Naeem",
  "Adnan Ali",
  "Irtaza Mehdi",
  "Asif Ali khan",
  "Cristiano Ronaldo",
  "Lionel Messi",
  "Danish Ali",
  "Abrar Ali",
  "Abdullah khan",
  "FAST NUCES",
  "Karachi Kings",
  "Multan Sultans",
  "Lahore Qalanadar",
  "Shazil Sattar",
  "Areeba khan",
  "Hafiz Imran",
  "hafiz Usman",
  "David Malan",
  "Nemar Jr",
  "Kylian Mbappe",
  "Luis Suarz",
  "Benzema Ben",
  "Islamabad United",
  "Peshawar zalimi",
  "FC Barcelona",
  "Real Madrid",
  "Pakistan",
  "Bayern Munich",
  "Argentine Football",
];
